;;; TOOL: run-interp-spec
;;; STDIN_FILE: third_party/testsuite/proposals/exception-handling/exports.wast
;;; ARGS*: --enable-exceptions
(;; STDOUT ;;;
out/test/spec/exception-handling/exports.wast:39: assert_invalid passed:
  0000000: error: function variable out of range: 0 (max 0)
  000000f: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:43: assert_invalid passed:
  0000000: error: function variable out of range: 1 (max 1)
  0000019: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:47: assert_invalid passed:
  0000000: error: function variable out of range: 1 (max 1)
  000002e: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:51: assert_invalid passed:
  error: duplicate export "a"
  000001d: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:55: assert_invalid passed:
  error: duplicate export "a"
  000001e: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:59: assert_invalid passed:
  error: duplicate export "a"
  0000025: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:63: assert_invalid passed:
  error: duplicate export "a"
  0000023: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:67: assert_invalid passed:
  error: duplicate export "a"
  0000022: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:71: assert_invalid passed:
  error: duplicate export "t0"
  0000022: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:100: assert_invalid passed:
  0000000: error: global variable out of range: 0 (max 0)
  000000f: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:104: assert_invalid passed:
  0000000: error: global variable out of range: 1 (max 1)
  0000017: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:108: assert_invalid passed:
  0000000: error: global variable out of range: 1 (max 1)
  0000029: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:112: assert_invalid passed:
  error: duplicate export "a"
  000001b: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:116: assert_invalid passed:
  error: duplicate export "a"
  0000020: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:120: assert_invalid passed:
  error: duplicate export "a"
  0000025: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:124: assert_invalid passed:
  error: duplicate export "a"
  0000021: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:128: assert_invalid passed:
  error: duplicate export "a"
  0000020: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:155: assert_invalid passed:
  0000000: error: table variable out of range: 0 (max 0)
  000000f: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:159: assert_invalid passed:
  0000000: error: table variable out of range: 1 (max 1)
  0000015: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:163: assert_invalid passed:
  0000000: error: table variable out of range: 1 (max 1)
  0000026: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:167: assert_invalid passed:
  error: duplicate export "a"
  0000019: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:171: assert_invalid passed:
  error: duplicate export "a"
  000001c: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:175: assert_invalid passed:
  error: duplicate export "a"
  0000023: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:179: assert_invalid passed:
  error: duplicate export "a"
  0000021: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:183: assert_invalid passed:
  error: duplicate export "a"
  000001e: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:211: assert_invalid passed:
  0000000: error: memory variable out of range: 0 (max 0)
  000000f: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:215: assert_invalid passed:
  0000000: error: memory variable out of range: 1 (max 1)
  0000014: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:219: assert_invalid passed:
  0000000: error: memory variable out of range: 1 (max 1)
  0000026: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:223: assert_invalid passed:
  error: duplicate export "a"
  0000018: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:232: assert_invalid passed:
  error: duplicate export "a"
  0000022: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:236: assert_invalid passed:
  error: duplicate export "a"
  0000020: error: OnExport callback failed
out/test/spec/exception-handling/exports.wast:240: assert_invalid passed:
  error: duplicate export "a"
  000001e: error: OnExport callback failed
41/41 tests passed.
;;; STDOUT ;;)
