;;; TOOL: wast2wasm
;;; FLAGS: --future-exceptions
;;; ERROR: 1
(module
  (except $ex i32)
  (func (result i32)
    try $try1 (result i32)
      nop
      i32.const 7
    catch $ex
      nop
    catch_all
      rethrow $try 
    end
  )
)
(;; STDERR ;;;
TryBlock: don't know how to visit
;;; STDERR ;;)
